export const SuccessCode = 200;

export const mealCategories = [
    'Dinner',
    'Lunch',
    'Snack',
    'Dessert',
    'Side Dish',
    'Appetizer',
    'Snacks',
    'Breakfast',
    'Beverage',
];

export const ingredients = [
    'Pizza',
    'Italian',
    'Vegetarian',
    'Stir-fry',
    'Asian',
    'Cookies',
    'Dessert',
    'Baking',
    'Pasta',
    'Chicken',
    'Salsa',
    'Salad',
    'Quinoa',
    'Bruschetta',
    'Beef',
    'Caprese',
    'Shrimp',
    'Biryani',
    'Main course',
    'Indian',
    'Pakistani',
    'Karahi',
    'Keema',
    'Potatoes',
    'Kebabs',
    'Saag',
    'Roti',
    'Ramen',
    'Japanese',
    'Soup',
    'Tagine',
    'Chickpea',
    'Moroccan',
    'Bibimbap',
    'Korean',
    'Rice',
    'Moussaka',
    'Greek',
    'Butter chicken',
    'Curry',
    'Thai',
    'Lassi',
    'Mango',
    'Tiramisu',
    'Turkish',
    'Grilling',
    'Smoothie',
    'Blueberry',
    'Banana',
    'Elote',
    'Mexican',
    'Street food',
    'Borscht',
    'Russian',
    'Dosa',
    'Falafel',
    'Lebanese',
    'Wrap',
    'Caipirinha',
    'Brazilian',
    'Cocktail',
    'Patatas bravas',
    'Spanish',
    'Spring rolls',
    'Vietnamese',
    'Quinoa salad',
    'Mediterranean',
    'Matcha ice cream',
    'Brigadeiros',
    'Enchiladas',
    'Shrimp curry',
    'Spanakopita',
    'Couscous salad',
    'Mojito',
    'Cuban',
    'Teriyaki chicken',
    'Mango salsa',
    'Shrimp stir-fry',
    'Quick',
    'Margherita pizza',
    'Pesto pasta',
    'Chicken skewers',
    'Hawaiian',
    'Sushi rolls',
    'Chickpea salad',
    'Pineapple',
    'Coconut'
];